//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vizegorselsinavi22.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_idari
    {
        public int idariid { get; set; }
        public string idariAdSoyad { get; set; }
        public string idariUnvan { get; set; }
        public Nullable<System.DateTime> idariBasla { get; set; }
        public Nullable<System.DateTime> idariCikis { get; set; }
    }
}
