//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vizegorselsinavi22.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ogretmen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ogretmen()
        {
            this.tbl_ogrenciler = new HashSet<tbl_ogrenciler>();
        }
    
        public int ogretmenid { get; set; }
        public string ogretmenAd { get; set; }
        public string ogretmenSoyad { get; set; }
        public Nullable<System.DateTime> ogretmenBasla { get; set; }
        public Nullable<System.DateTime> ogretmenCikis { get; set; }
        public string ogretmenBolum { get; set; }
        public Nullable<int> ogretmenbolumid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ogrenciler> tbl_ogrenciler { get; set; }
        public virtual tbl_ogrenciler tbl_ogrenciler1 { get; set; }
    }
}
